// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "vipulsirdemo/models"

	mock "github.com/stretchr/testify/mock"
)

// CategoryRepository is an autogenerated mock type for the CategoryRepository type
type CategoryRepository struct {
	mock.Mock
}

// AddCategory provides a mock function with given fields: category
func (_m *CategoryRepository) AddCategory(category models.Category) {
	_m.Called(category)
}

// EditCategory provides a mock function with given fields: category
func (_m *CategoryRepository) EditCategory(category models.Category) {
	_m.Called(category)
}
