// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "vipulsirdemo/models"

	mock "github.com/stretchr/testify/mock"
)

// HobbiesRepository is an autogenerated mock type for the HobbiesRepository type
type HobbiesRepository struct {
	mock.Mock
}

// AddHobby provides a mock function with given fields: hobby
func (_m *HobbiesRepository) AddHobby(hobby models.Hobbies) {
	_m.Called(hobby)
}
