// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "vipulsirdemo/models"

	mock "github.com/stretchr/testify/mock"
)

// MenuRepository is an autogenerated mock type for the MenuRepository type
type MenuRepository struct {
	mock.Mock
}

// AddMenu provides a mock function with given fields: menu
func (_m *MenuRepository) AddMenu(menu models.Menu) {
	_m.Called(menu)
}

// EditMenu provides a mock function with given fields: menu
func (_m *MenuRepository) EditMenu(menu models.Menu) {
	_m.Called(menu)
}
