// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "vipulsirdemo/models"

	mock "github.com/stretchr/testify/mock"
)

// OrderMenuRepository is an autogenerated mock type for the OrderMenuRepository type
type OrderMenuRepository struct {
	mock.Mock
}

// AddOrderMenu provides a mock function with given fields: orderMenu
func (_m *OrderMenuRepository) AddOrderMenu(orderMenu models.OrderMenu) {
	_m.Called(orderMenu)
}

// GetOrderMenus provides a mock function with given fields: orderMenu
func (_m *OrderMenuRepository) GetOrderMenus(orderMenu models.OrderMenu) {
	_m.Called(orderMenu)
}
