// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "vipulsirdemo/models"

	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

// AddOrder provides a mock function with given fields: order
func (_m *OrderRepository) AddOrder(order models.Order) {
	_m.Called(order)
}

// GetOrder provides a mock function with given fields: order
func (_m *OrderRepository) GetOrder(order models.Order) {
	_m.Called(order)
}
