// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "vipulsirdemo/models"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// UserLogin provides a mock function with given fields: user
func (_m *UserRepository) UserLogin(user models.User) {
	_m.Called(user)
}

// UserSignUp provides a mock function with given fields: user
func (_m *UserRepository) UserSignUp(user models.User) {
	_m.Called(user)
}

// UserVerification provides a mock function with given fields: user
func (_m *UserRepository) UserVerification(user models.User) {
	_m.Called(user)
}
